version: '3.1'
services:

  app:
    image: tomcat-war
    build:
      context: .
    container_name: tomcat-war
    ports:
      - "8888:8080"
#    volumes:
#      - ./conf/your.jar:/usr/local/tomcat/webapps/
#    environment:
#      - JAVA_OPTS='-Xmx1g'
    restart: unless-stopped